#!/bin/bash
echo "Enter file name"
read filename
echo "Enter command"
read command
touch $filename
chmod u+x $filename
$firstline = "\#!/bin/bash"
echo -e "$firstline\n$command" > $filename
nano $filename
